import type { ReactNode } from 'react';

import clsx from 'clsx';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): ReactNode {
  return (
    <html lang="en" className="bg-custom-dark-light">
      <body
        className={clsx(
          inter.className,
          'overflow-y-hidden overflow-x-auto w-screen h-screen'
        )}
      >
        {children}
      </body>
    </html>
  );
}
